In [2]:
#Ejercicio 3.2.1. Crea un array con valores entre el 9 y el 24

import numpy

a = numpy.arange(9,25)
print(a)

[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [3]:
#Ejercicio 3.2.2. ¿Cuántos elementos tiene el array anterior?

import numpy

a = numpy.arange(9,25)
print(a.size)

16


In [4]:
#Ejercicio 3.2.3. Crea un array con los mismos valores pero que tenga 2 filas y 8 columna

import numpy

a = numpy.arange(9,25).reshape(2,8)

print(a)


[[ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]


In [5]:
#Ejercicio 3.2.4.Crea un array con los mismos valores pero ahora con 3 filas y 4 columnas.

import numpy

a = numpy.arange(9,25).reshape(3,4)

print(a)


ValueError: cannot reshape array of size 16 into shape (3,4)

In [11]:
#Ejercicio 3.2.5.
#Crea un array con los valores 3,5,6,1,7,9,2,3,6. 
#Recorre el array y escribe una letra del abecedario por pantalla, la que tú quieras, siempre que los valores del array sean mayores que 5.

import pandas

a = pandas.Series([3,5,6,1,7,9,2,3,6])
for l in a:
    if l > 5:
        print("A")

A
A
A
A


In [18]:
#Ejercicio 3.2.6.
#Dados dos arrays, a y b, con valores, 1,2,3 y 4,5,6 respectivamente. 
#Calcula la división de a entre b y muestra por pantalla un nuevo array cuyos elementos serán,
#los valores de a, los valores de b y el resultado de la división entre a y b.

import numpy

a = numpy.array([1,2,3])
b = numpy.array([4,5,6])
c = a/b
resultado = numpy.array([a,b,c])
print(resultado)



[[1.   2.   3.  ]
 [4.   5.   6.  ]
 [0.25 0.4  0.5 ]]


In [21]:
#Ejercicio 3.2.7.
#Dados los dos arrays anteriores, con valores 1,2,3 y 4,5,6 respectivamente, multiplícalos por 6 y muestra por pantalla el resultado.

import numpy

a = numpy.array([1,2,3])
b = numpy.array([4,5,6])

mul_a = (a*6)
mul_b = (b*6)

print(mul_a)
print(mul_b)


[ 6 12 18]
[24 30 36]


In [23]:
#Ejercicio 3.2.8.
#¿Qué dimensión tiene el array que has obtenido en el ejercicio anterior, es decir, cuántas filas y columnas tiene? 
#Y, ¿de qué tipo son los elementos que los forman?

import numpy

a = numpy.array([1,2,3])
b = numpy.array([4,5,6])

mul_a = (a*6)
mul_b = (b*6)

multiplicacion = numpy.array([mul_a, mul_b])

print(multiplicacion.shape)
print(multiplicacion.dtype)



(2, 3)
int64


In [25]:
#Ejercicio 3.2.9.
#Crea una serie que contenga los datos 4,8,6,2,7,8,2,1,9 y muéstrala por pantalla.

import pandas

serie=pandas.Series([4,8,6,2,7,8,2,1,9])
print(serie)



0    4
1    8
2    6
3    2
4    7
5    8
6    2
7    1
8    9
dtype: int64


In [28]:
#Ejercicio 3.2.10.
#Vuelve a crear la serie anterior, pero esta vez, haz que sus índices contengan las letras del abecedario, comenzando por la a.

import pandas

serie=pandas.Series([4,8,6,2,7,8,2,1,9], index=['a', 'b','c','d','e','f','g','h','i'])
print(serie)

#import string
#indices = list(string.ascii_lowercase)[:len(numeros)]


a    4
b    8
c    6
d    2
e    7
f    8
g    2
h    1
i    9
dtype: int64


In [29]:
#Ejercicio 3.2.11. ¿Qué valor tiene el elemento con índice e?
import pandas

serie=pandas.Series([4,8,6,2,7,8,2,1,9], index=['a', 'b','c','d','e','f','g','h','i'])
print(serie['e'])



7


In [30]:
#Ejercicio 3.2.12.
#Dadas dos series, a y b, formadas por los elementos 1,5,3,8 y 4,8,3,9, 
#muestra por pantalla otra serie que contenga los restos de dividir a entre b.

import pandas
a = pandas.Series([1,5,3,8])
b = pandas.Series([4,8,3,9])
resto = a%b

print(resto)

0    1
1    5
2    0
3    8
dtype: int64


In [32]:
#Ejercicio 3.2.13. Dada la serie 1,4,6,8 muestra por pantalla el resultado de multiplicarla por 4.

import pandas

serie = pandas.Series([1,4,6,8])
print (serie*4)

0     4
1    16
2    24
3    32
dtype: int64


In [110]:
#Ejercicio 3.2.14.Crea una serie con los elementos 4,8,6,2,7,8,2,1,9. 
#devuelve otra serie cuyo primer elemento sea la suma del primer y el segundo elemento de la serie creada en un principio, 
#cuyo segundo elemento sea la suma del segundo y el tercer elemento de la serie creada al principio, 
#cuyo tercer elemento sea la suma del tercer y el cuarto elemento de la serie creada en un principio, 
#y así hasta incluir todos los elementos de la serie creada en un principio.

import pandas

serie = pandas.Series ([4,8,6,2,7,8,2,1,9])

resultado = []

for i in range(len(serie)-1):
    suma=serie[i] + serie[i+1]
    resultado.append(suma)

nueva_serie = pandas.Series(resultado)
print((nueva_serie).to_numpy())



[12 14  8  9 15 10  3 10]


In [38]:
#Ejercicio 3.3.1. Crea un dataframe que contenga cuatro columnas, 
#una de ella tendrá los meses de año (Mes), 
#otra tendrá los importes que se han facturado cada uno de esos meses (Ventas), 
#en concreto 10000, 15200, 14300, 25800, 2560, 12780, 32500, 23624, 12000,15858, 23250, 11630; 
#la tercera columna tendrá los gastos realizados ese mes (Gastos), 
#en concreto 6500, 6500, 6500, 7850, 6500, 8250, 6500, 9252, 6500,10250, 12450, 13000; 
#la última columna tendrá una S o una N en función de si se han cobrado ese mes la totalidad de las ventas (Cobrado), 
#en concreto S, N, N, S, S, N, S, S, S, N, S, N.

import pandas

datos = {'Mes':['Enero','Febrero','Marzo','Abril','Mayo','Junio', 'Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
         'Ventas':[10000, 15200, 14300, 25800, 2560, 12780, 32500, 23624, 12000,15858, 23250, 11630], 
         'Gastos':[6500, 6500, 6500, 7850, 6500, 8250, 6500, 9252, 6500,10250, 12450, 13000],
         'Cobrado':['S','N','N','S','S','N','S','S','S','N','S','N']}
df_datos = pandas.DataFrame(datos)
print(df_datos)

           Mes  Ventas  Gastos Cobrado
0        Enero   10000    6500       S
1      Febrero   15200    6500       N
2        Marzo   14300    6500       N
3        Abril   25800    7850       S
4         Mayo    2560    6500       S
5        Junio   12780    8250       N
6        Julio   32500    6500       S
7       Agosto   23624    9252       S
8   Septiembre   12000    6500       S
9      Octubre   15858   10250       N
10   Noviembre   23250   12450       S
11   Diciembre   11630   13000       N


In [67]:
'''Pregunta 1: ¿Cuántas filas tiene el dataframe?
Pregunta 2: ¿Cuáles son las columnas que los forman?
Pregunta 3: ¿Cuánto espacio ha utilizado en memoria?
Pregunta 4: ¿Cuál es la media de las ventas anuales?
Pregunta 5: Teniendo en cuenta solo las columnas Ventas y Gastos, al final de año, ¿crees que la empresa es rentable?'''

import pandas
import sys


datos = {'Mes':['Enero','Febrero','Marzo','Abril','Mayo','Junio', 'Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
         'Ventas':[10000, 15200, 14300, 25800, 2560, 12780, 32500, 23624, 12000,15858, 23250, 11630], 
         'Gastos':[6500, 6500, 6500, 7850, 6500, 8250, 6500, 9252, 6500,10250, 12450, 13000],
         'Cobrado':['S','N','N','S','S','N','S','S','S','N','S','N']}
df_datos = pandas.DataFrame(datos)
print(f'¿Cuántas filas tiene el dataframe? {df_datos.shape[0]}')
print(f'¿Cuáles son las columnas que los forman? {df_datos.columns}')
print(f'¿Cuánto espacio ha utilizado en memoria? {sys.getsizeof(datos)} bytes')
print(f'¿Cuál es la media de las ventas anuales?', df_datos["Ventas"].mean())
print(f'Si la diferencia entre ventas y gastos es positiva, la empresa es rentable. Resultado=', (df_datos["Ventas"].sum()-df_datos["Gastos"].sum()))

¿Cuántas filas tiene el dataframe? 12
¿Cuáles son las columnas que los forman? Index(['Mes', 'Ventas', 'Gastos', 'Cobrado'], dtype='object')
¿Cuánto espacio ha utilizado en memoria? 232 bytes
¿Cuál es la media de las ventas anuales? 16625.166666666668
Si la diferencia entre ventas y gastos es positiva, la empresa es rentable. Resultado= 99450


In [75]:
'''Ejercicio 3.3.3.
Muestra toda la información sobre los meses en los que se ha facturado por encima de la facturación media anual'''


import pandas

datos = {'Mes':['Enero','Febrero','Marzo','Abril','Mayo','Junio', 'Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
         'Ventas':[10000, 15200, 14300, 25800, 2560, 12780, 32500, 23624, 12000,15858, 23250, 11630], 
         'Gastos':[6500, 6500, 6500, 7850, 6500, 8250, 6500, 9252, 6500,10250, 12450, 13000],
         'Cobrado':['S','N','N','S','S','N','S','S','S','N','S','N']}
df_datos = pandas.DataFrame(datos)
media_anual = df_datos["Ventas"].mean()
df_datos [df_datos['Ventas']>media_anual]

Mes  Ventas  Gastos Cobrado
3       Abril   25800    7850       S
6       Julio   32500    6500       S
7      Agosto   23624    9252       S
10  Noviembre   23250   12450       S

In [96]:
'''Ejercicio 3.3.4.
Muestra los meses en los que hay facturas pendientes de cobro, es decir, los meses en los que no se han cobrado todas las facturas'''

import pandas

datos = {'Mes': ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
         'Ventas': [10000, 15200, 14300, 25800, 2560, 12780, 32500, 23624, 12000, 15858, 23250, 11630],
         'Gastos': [6500, 6500, 6500, 7850, 6500, 8250, 6500, 9252, 6500, 10250, 12450, 13000],
         'Cobrado': ['S', 'N', 'N', 'S', 'S', 'N', 'S', 'S', 'S', 'N', 'S', 'N']}
df_datos = pandas.DataFrame(datos)

cobrado = df_datos[df_datos['Cobrado'] == 'N'].drop(['Ventas', 'Gastos'], axis=1) #nombro lo que quiero eliminar.uso axis para mantener la 1
#mejor df.loc[df['Cobrado'] == 'N', [´Mes']]
print(cobrado)


          Mes Cobrado
1     Febrero       N
2       Marzo       N
5       Junio       N
9     Octubre       N
11  Diciembre       N


In [98]:
'''Ejercicio 3.3.5.
Utilizando el mismo dataframe, muestra toda la información sobre los meses en los que los gastos han sido mayores que las ventas.'''

import pandas

datos = {'Mes': ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
         'Ventas': [10000, 15200, 14300, 25800, 2560, 12780, 32500, 23624, 12000, 15858, 23250, 11630],
         'Gastos': [6500, 6500, 6500, 7850, 6500, 8250, 6500, 9252, 6500, 10250, 12450, 13000],
         'Cobrado': ['S', 'N', 'N', 'S', 'S', 'N', 'S', 'S', 'S', 'N', 'S', 'N']}
df_datos = pandas.DataFrame(datos)
reporte = df_datos[df_datos['Gastos']>df_datos['Ventas']]
print (reporte)


          Mes  Ventas  Gastos Cobrado
4        Mayo    2560    6500       S
11  Diciembre   11630   13000       N


In [102]:
'''Ejercicio 3.3.6.
Añade una nueva columna al dataframe que hemos estado utilizando, llamada Beneficio, que tenga sus doce valores iguales a 0.

NOTA: Crea un nuevo dataframe utilizando diccionarios y lo que sabes sobre ellos.'''

import pandas

datos = {'Mes': ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
         'Ventas': [10000, 15200, 14300, 25800, 2560, 12780, 32500, 23624, 12000, 15858, 23250, 11630],
         'Gastos': [6500, 6500, 6500, 7850, 6500, 8250, 6500, 9252, 6500, 10250, 12450, 13000],
         'Cobrado': ['S', 'N', 'N', 'S', 'S', 'N', 'S', 'S', 'S', 'N', 'S', 'N']}
df_datos = pandas.DataFrame(datos)
df_datos['Beneficio']=0
df_datos

Mes  Ventas  Gastos Cobrado  Beneficio
0        Enero   10000    6500       S          0
1      Febrero   15200    6500       N          0
2        Marzo   14300    6500       N          0
3        Abril   25800    7850       S          0
4         Mayo    2560    6500       S          0
5        Junio   12780    8250       N          0
6        Julio   32500    6500       S          0
7       Agosto   23624    9252       S          0
8   Septiembre   12000    6500       S          0
9      Octubre   15858   10250       N          0
10   Noviembre   23250   12450       S          0
11   Diciembre   11630   13000       N          0

In [105]:
import pandas

datos = {'Mes': ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
         'Ventas': [10000, 15200, 14300, 25800, 2560, 12780, 32500, 23624, 12000, 15858, 23250, 11630],
         'Gastos': [6500, 6500, 6500, 7850, 6500, 8250, 6500, 9252, 6500, 10250, 12450, 13000],
         'Cobrado': ['S', 'N', 'N', 'S', 'S', 'N', 'S', 'S', 'S', 'N', 'S', 'N']}
df_datos = pandas.DataFrame(datos)
df_datos['Beneficio']= (df_datos['Ventas']-df_datos['Gastos'])
df_datos

Mes  Ventas  Gastos Cobrado  Beneficio
0        Enero   10000    6500       S       3500
1      Febrero   15200    6500       N       8700
2        Marzo   14300    6500       N       7800
3        Abril   25800    7850       S      17950
4         Mayo    2560    6500       S      -3940
5        Junio   12780    8250       N       4530
6        Julio   32500    6500       S      26000
7       Agosto   23624    9252       S      14372
8   Septiembre   12000    6500       S       5500
9      Octubre   15858   10250       N       5608
10   Noviembre   23250   12450       S      10800
11   Diciembre   11630   13000       N      -1370

In [109]:
'''Ejercicio 3.3.8.
Con el nuevo dataframe obtenido el ejercicio anterior, muestra cuales son los meses en los que ha habido pérdidas.
¿Coinciden las respuestas de este ejercicio y del ejercicio 3.3.5? ¿Deberían coincidir?'''
import pandas

datos = {'Mes': ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
         'Ventas': [10000, 15200, 14300, 25800, 2560, 12780, 32500, 23624, 12000, 15858, 23250, 11630],
         'Gastos': [6500, 6500, 6500, 7850, 6500, 8250, 6500, 9252, 6500, 10250, 12450, 13000],
         'Cobrado': ['S', 'N', 'N', 'S', 'S', 'N', 'S', 'S', 'S', 'N', 'S', 'N']}
df_datos = pandas.DataFrame(datos)
df_datos['Beneficio']= (df_datos['Ventas']-df_datos['Gastos'])
reporte2 = df_datos[df_datos['Beneficio']<0]
print (reporte2)


          Mes  Ventas  Gastos Cobrado  Beneficio
4        Mayo    2560    6500       S      -3940
11  Diciembre   11630   13000       N      -1370


In [6]:
'''Ejercicio 3.3.9.
Muestra todos los datos sobre el mes en el que hay un mayor beneficio.'''

import pandas

datos = {'Mes': ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
         'Ventas': [10000, 15200, 14300, 25800, 2560, 12780, 32500, 23624, 12000, 15858, 23250, 11630],
         'Gastos': [6500, 6500, 6500, 7850, 6500, 8250, 6500, 9252, 6500, 10250, 12450, 13000],
         'Cobrado': ['S', 'N', 'N', 'S', 'S', 'N', 'S', 'S', 'S', 'N', 'S', 'N']}
df_datos = pandas.DataFrame(datos)
df_datos['Beneficio']= (df_datos['Ventas']-df_datos['Gastos'])
df_datos[df_datos['Beneficio']==df_datos['Beneficio'].max()]

Mes  Ventas  Gastos Cobrado  Beneficio
6  Julio   32500    6500       S      26000

In [7]:
'''Ejercicio 3.3.10.
Muestra los meses en los que el beneficio ha sido mayor que la media de los beneficios anuales, aunque no se hayan cobrado aún todas las facturas'''


import pandas

datos = {'Mes': ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
         'Ventas': [10000, 15200, 14300, 25800, 2560, 12780, 32500, 23624, 12000, 15858, 23250, 11630],
         'Gastos': [6500, 6500, 6500, 7850, 6500, 8250, 6500, 9252, 6500, 10250, 12450, 13000],
         'Cobrado': ['S', 'N', 'N', 'S', 'S', 'N', 'S', 'S', 'S', 'N', 'S', 'N']}
df_datos = pandas.DataFrame(datos)
df_datos['Beneficio']= (df_datos['Ventas']-df_datos['Gastos'])
df_datos[df_datos['Beneficio']>df_datos['Beneficio'].mean()]

Mes  Ventas  Gastos Cobrado  Beneficio
1     Febrero   15200    6500       N       8700
3       Abril   25800    7850       S      17950
6       Julio   32500    6500       S      26000
7      Agosto   23624    9252       S      14372
10  Noviembre   23250   12450       S      10800